# Generated by Django 6.0.3 on 2026-03-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=50)),
                ('route_name', models.CharField(max_length=100)),
                ('coordinates', models.JSONField()),
                ('waypoints', models.JSONField()),
            ],
        ),
    ]
