# Generated by Django 6.0.3 on 2026-05-09 07:35

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institute_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('razorpay_order_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institute', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=50)),
                ('route_name', models.CharField(max_length=100)),
                ('coordinates', models.JSONField()),
                ('waypoints', models.JSONField()),
                ('is_active', models.BooleanField(default=False)),
                ('live_latitude', models.FloatField(blank=True, null=True)),
                ('live_longitude', models.FloatField(blank=True, null=True)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.OneToOneField(blank=True, limit_choices_to={'profile__role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_route', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='institute.institute')),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('bus_no'), models.F('institute'), name='unique_route_bus_no_per_institute', violation_error_message='This bus number already exists in your institute.'), models.UniqueConstraint(django.db.models.functions.text.Lower('route_name'), models.F('institute'), name='unique_route_name_per_institute', violation_error_message='This route name already exists in your institute.')],
            },
        ),
    ]
