# Generated by Django 6.0.3 on 2026-05-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
