# Generated by Django 6.0.3 on 2026-03-18 12:10

from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                Lower("bus_no"),
                name="unique_route_bus_no_ci",
                violation_error_message="This bus number already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                Lower("route_name"),
                name="unique_route_name_ci",
                violation_error_message="This route name already exists.",
            ),
        ),
    ]
