# Generated by Django 6.0.3 on 2026-05-12 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_institute_razorpay_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='E.g. "Morning Pickup", "Evening Return"', max_length=100)),
                ('departure_time', models.TimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='institute.route')),
            ],
            options={
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order_index', models.PositiveIntegerField(help_text='Order of this stop along the route (0 = first stop).')),
                ('eta_minutes', models.PositiveIntegerField(default=0, help_text='Auto-computed cumulative minutes from departure.')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='institute.route')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('route', 'order_index')},
            },
        ),
    ]
