# Generated by Django 6.0.3 on 2026-04-29 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_route_unique_bus_no_ci_route_unique_route_name_ci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='driver',
            field=models.OneToOneField(blank=True, limit_choices_to={'profile__role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_route', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
