# Generated by Django 6.0.3 on 2026-05-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_route_driver_route_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='live_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='live_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
